name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Restoring Frontend Dependencies
      env:
        AppInsightsInstrumentKey: ${{secrets.APPINSIGHTS_INSTRUMENTKEY}}
      run: |
        cd front_src
        printf "`r`nimport `{ Imogene as `$ `} from '../Imogene/Imogene'; import { ApplicationInsights } from '@microsoft/applicationinsights-web'; `$`(`(`) => `{ const i = new ApplicationInsights`(`{ config: `{ instrumentationKey: '$env:AppInsightsInstrumentKey' `} `}); i.loadAppInsights(), i.trackPageView() `});`r`n" > "main/appinsights.js"
        npm ci
        cd ..
      shell: powershell
    - name: Build Frontend
      run: .\Prepare-Frontend.ps1
      shell: powershell
    - name: Restore dependencies for Backend
      run: dotnet restore
    - name: Build Backend
      run: dotnet build --no-restore --configuration Release
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
