name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Frontend
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: "Prepare-Frontend.ps1"
    - name: Restore dependencies for Backend
      run: dotnet restore
    - name: Build Backend
      run: dotnet build --no-restore "DerekHoneycutt/DerekHoneycutt.csproj" --configuration Release
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
